language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - nightly
notifications:
  email: false
git:
  depth: 99999999


after_success:
  # push coverage results to Coveralls
  - julia -e 'using Compat.Pkg; cd(Pkg.dir("Discreet")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Compat.Pkg; cd(Pkg.dir("Discreet")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
